### ISSUE TITLE
主页新闻界面对齐问题

### ISSUE THREAD

**Issue by XTKKKKK** [JJAYCHENooo/MeetHere-frontend#10]
主页的新闻界面跑马灯对齐有误，没有做到全部中心对齐

**Comment by XTKKKKK** [comment]
没有对齐是因为样式的嵌套出错，将对应div的css布局改为flex即可

**Comment by XTKKKKK** [comment]
### 跑马灯实现原理
#### 跑马灯模块中有三部分内容，
- 新闻的标题newsTextTitle
- 新闻的内容 newsTextContent
- 新闻的时间newsTextTime
这三个div打包成一个div newsText。这样的好处是可以通过设置newsTextContent的height属性让newsTextContent自适应占满。

### 修复跑马灯格式出错问题
设置newsTextContent的css的display属性

```css
.newsTextContent{
  line-height: 30px;
  height : 210px;
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;/*垂直居中*/
  justify-content: center; /* 水平居中 */
  align-items: center;
}
```
即可修复问题
